### ISSUE TITLE
Pi

### ISSUE THREAD

**Issue by imukai** [bijington/expressive#37]
Are there plans to implement a constant for pi?

**Comment by bijington** [comment]
I didn’t have any real plans to as I originally didn’t want to have to keep
adding new constants. That said I am not against adding it in now.

Currently you could use [Pi] and supply it as a variable but I will aim to
try and get it in the next release which will likely be out soon.

Out of interest are there any other constants you would be interested in
using?

**Comment by bijington** [comment]
Thanks, I will go through that list a bit more thoroughly and see what makes sense to include. I think for the time being it will probably involve a minimal set of constants but I will expose a mechanism for users to register their own constants making it fairly extensible.

On the point about the ^ symbol, unfortunately because this framework does more than just mathematical operations that symbol has another purpose. It currently operates as a Bitwise Exclusive Or (https://docs.microsoft.com/en-us/cpp/cpp/bitwise-exclusive-or-operator-hat?view=vs-2017)

**Comment by bijington** [comment]
Slipped back out of this release but will hopefully be achievable in the next release

**Comment by bijington** [comment]
The plan for constants at least for the short term will be to expose them as parameterless functions much like Excel does e.g.

`PI()` will return the Pi constant.

**Comment by bijington** [comment]
Solved by PR #92 `PI()` and `E()` are now available as constant functions.

**Comment by bijington** [comment]
Fixed and shipped in release v2.3.0
