### ISSUE TITLE
Unable to directly cast.

### ISSUE THREAD

**Issue by IkerRuizArnauda** [bijington/expressive#8]
Test expression: 19.2 \* exp(-0.4_(2/2+8)) \* cos(0.1_(2/2+8))+1

"-0.4" TypeCode is decimal and "2/2+8" (9) TypeCode double.

In numbers.cs when trying to perform the multiplication:

Line:
case TypeCode.Double: return (Decimal)a \* (Decimal)b; // <- This fails.

Changed it to:
case TypeCode.Double: return Convert.ToDecimal(a) \* Convert.ToDecimal(b); // <- This works.
or
case TypeCode.Double: return return decimal.Parse(a.ToString()) \* decimal.Parse(b.ToString()); // <- This also works.

Im not sure whats the underlying issue here but since data types are being boxed/unboxed/converted in different places, that might be messing with the actual Type of the boxed value. But this issue with direct casting might affect other types as single/int/decimal/etc..

After using Parse or ConvertTo this expression result is: 1.326106 which is correct.

**Comment by bijington** [comment]
Hi  @IkerRuizArnauda ,

Thank you for the bug report, it is nice to know someone else is using my code :).

Unfortunately I think you may have found more than 1 issue as this section of your expression: -0.4(2/2+8) actually evaluates to -0.4. The framework doesn't currently allow for implicit multiplication and for some reason it is not detecting the trailing components as being invalid (I will raise this as a separate ticket).

Now on to your actual issue. You mention that the following line fails:
`case TypeCode.Double: return (Decimal)a * (Decimal)b; // <- This fails.`
Is this a change that you made because my source is actually this line:
`case TypeCode.Double: throw new InvalidOperationException("Operator '*' can't be applied to operands of types 'decimal' and 'double'");`

I originally tried to match the .NET framework which does not allow multiplying a `Double` and a `Decimal` and therefore I threw an Exception to prevent this case but I think we can provide a way of achieving the calculation.

I do have 2 possible solutions for you although I have to be honest I am not entirely sure which one I would like to go with myself for now. I will need to have a further think on it and I will update this case later when I come to a conclusion on the best approach. For now though here are the options:

1. Convert to Decimal
 You can do the following:
`case TypeCode.Double: return (Decimal)a * Convert.ToDecimal(b);`
`a` is already a `Decimal` so there is no point converting it but b does need to be converted. This will now give you the result  **1.3261062062751612694741274423**.

2. Change the order of parsing
This does actually point me to the parsing logic as currently it attempts to extract number values in the following order:
`Int`
`Decimal`
`Double`
`Float`
`Long`
If the order is changed to parse `Double`s first then it will also solve your issue. In order to do that simply move the `decimal.TryParse` statement in ExpressionParser.cs line 326 to below the `double.TryParse`. This will give you the result **1.326106206275161**. 

I did originally plan on parsing to Decimal first in order to give better accuracy as you can see from the different results returned from the 2 above solutions.

You are certainly correct about the possibility of further accuracy problems I did bring this part of the  and I will try to now push the framework to see if I can identify any further holes.

**Comment by IkerRuizArnauda** [comment]
For now I ended up handling every numeric type as Decimal, this fixed different exceptions indluding invalid cast and overflow exeptions when doing certain divisions (Not division by zero). Of course I ended up high huge numbers but its fine. Will keep an eye on further changes. Thanks

**Comment by bijington** [comment]
This should hopefully now be resolved through the following fixes/changes:

[Issue 22 -Fractional values are defaulting to Decimal data type](https://github.com/bijington/expressive/issues/22)

[Issue #20 - Add in the ability to convert values]
(https://github.com/bijington/expressive/issues/20)
